export const userInputs = [
  {
    id: 1,
    label: "Username",
    name: "username",
    type: "text",
    placeholder: "ng_dien",
  },
  // {
  //   id: 2,
  //   label: "Name and Surname",
  //   name: "name",
  //   type: "text",
  //   placeholder: "Smith Rowe",
  // },
  {
    id: 3,
    label: "Email",
    name: "email",
    type: "email",
    placeholder: "ng_diene@gmail.com",
  },
  // {
  //   id: 4,
  //   label: "Phone",
  //   name: "phone",
  //   type: "text",
  //   placeholder: "+1 234-234-545",
  // },
  {
    id: 5,
    label: "Password",
    name: "password",
    type: "password",
    placeholder: "Enter your password",
  },
  // {
  //   id: 6,
  //   label: "Address",
  //   name: "address",
  //   type: "text",
  //   placeholder: "Melwood str. Liverpool",
  // },
  // {
  //   id: 6,
  //   label: "Country",
  //   name: "country",
  //   type: "text",
  //   placeholder: "United Kingdom",
  // },
];
